export const CODE_EXECUTION_STATUS = ['EXECUTING', 'COMPLETED'] as const;
export const RESULT_OF_EXECUTION = ['PASSED', 'FAILED'] as const;

export const SCORE_WEIGHTS = {
  ACCEPTED_BONUS: 100,
  PER_TESTCASE_PASSED: 10,
  ATTEMPT_PENALTY: 5,
  TIME_BONUS_CAP: 2000,
  TIME_BONUS_DIVISOR: 200,
} as const;
