export const CODE_EXECUTION_STATUS = ['EXECUTING', 'COMPLETED'] as const;
export const RESULT_OF_EXECUTION = [
  'SUCCESS',
  'FAILED',
  'TIME_LIMIT_EXCEEDED',
  'RESOURCE_LIMIT_EXCEEDED',
  'RUNTIME_ERROR',
  'INTERNAL_ERROR',
] as const;

export const SCORE_WEIGHTS = {
  ACCEPTED_BONUS: 100,
  PER_TESTCASE_PASSED: 10,
  ATTEMPT_PENALTY: 5,
  TIME_BONUS_CAP: 2000,
  TIME_BONUS_DIVISOR: 200,
} as const;
